Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate  on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vectorized operations.


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
print(arr.shape)

print(arr.dtype)
print(type(arr))

(5,)
int32
<class 'numpy.ndarray'>


In [4]:
arr.reshape(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr.ndim

1

In [15]:
# numpy array vectorizing
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.array([11, 12, 13, 14, 15])

print("Addition",arr1 + arr2 + arr3)
print("Subtraction",arr1 - arr2 - arr3)
print("Multiplication",arr1 * arr2 * arr3)
print("Division",arr1 / arr2 / arr3)



Addition [18 21 24 27 30]
Subtraction [-16 -17 -18 -19 -20]
Multiplication [ 66 168 312 504 750]
Division [0.01515152 0.02380952 0.02884615 0.03174603 0.03333333]


 ## array slicing and indexing

In [17]:
arr5 = np.array([[1, 2, 3, 4, 5],
                 [2, 3, 4, 5, 6],
                 [3, 4, 5, 6, 7]])

In [23]:
arr5[1:]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [25]:
arr5[1:,3:]

array([[5, 6],
       [6, 7]])

In [26]:
arr5[0:2, 3:]

array([[4, 5],
       [5, 6]])

In [27]:
arr5[1:, 1:3]

array([[3, 4],
       [4, 5]])

In [28]:
arr5[0,0] = 1000

In [29]:
arr5

array([[1000,    2,    3,    4,    5],
       [   2,    3,    4,    5,    6],
       [   3,    4,    5,    6,    7]])

### Statistical concepts... Normalizaiton

In [33]:
data = np.array([1, 2, 3, 4, 5])

#calculate the mean 
mean =np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data - mean) / std_dev

print("Normalized Data : ", normalized_data)
print(" Mean : ",np.mean(data))
print(" Median : ",np.median(data))
print(" Standard Deviation : ",np.std(data))
print(" Variance : ",np.var(data))

Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
 Mean :  3.0
 Median :  3.0
 Standard Deviation :  1.4142135623730951
 Variance :  2.0


In [ ]:
data>2


array([False, False,  True,  True,  True])

In [36]:
data[data>2]

array([3, 4, 5])