Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate  on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vectorized operations.


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
print(arr.shape)

print(arr.dtype)
print(type(arr))

(5,)
int32
<class 'numpy.ndarray'>


In [4]:
arr.reshape(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])